# Generated by Django 2.2 on 2019-04-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='otherinfo',
            unique_together={('content_type', 'object_id', 'medicine')},
        ),
    ]
