# Generated by Django 2.2 on 2019-04-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190428_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='mean',
            new_name='mean_demand',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='sd',
            new_name='sd_of_demand',
        ),
    ]
